-- Auto-generated by scripts/generate-seed.mjs — do not edit by hand.
-- Run `node scripts/generate-seed.mjs` to regenerate.

begin;

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'breakfast',
  'Overnight Oats',
  'breakfast',
  905, 54, 93, 36,
  '[{"name":"Rolled oats","amount":"85g","amount_value":85,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Unsweetened soy milk","amount":"250ml","amount_value":250,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Whey protein powder","amount":"30g (1 scoop)","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Peanut butter","amount":"20g","amount_value":20,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chia seeds OR ground flaxseed","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Banana (or seasonal fruit)","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cacao nibs OR mixed nuts (walnuts, almonds)","amount":"10g","amount_value":10,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["The night before: add oats, soy milk, and chia seeds (or ground flaxseed) to a jar or bowl. Stir well — seeds clump if left unstirred.","Stir in whey protein powder until fully dissolved. Soy milk helps it incorporate smoothly.","Stir in peanut butter.","Seal and refrigerate overnight — minimum 6h, up to 24h. The oats will absorb the liquid and thicken.","In the morning: stir, add a splash of soy milk if too thick. Top with sliced banana and cacao nibs or a small handful of nuts for crunch."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'snack',
  'Protein Bar',
  'snack',
  220, 20, 20, 6,
  '[{"name":"Generic protein bar (~200–250 kcal, ~20g protein)","amount":"1 bar","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Mid-afternoon, ideally 2–3h away from training."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L1',
  'Tuna Pasta Arrabbiata',
  'lunch',
  1040, 59, 128, 20,
  '[{"name":"Penne rigate (dry)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Passata","amount":"200ml","amount_value":200,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried chilli flakes","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cherry tomatoes","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh parsley","amount":"small handful","amount_value":1000,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & black pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Boil well-salted water. Cook penne 1 min less than packet says.","Sauté sliced garlic in olive oil 1 min. Add chilli flakes and halved cherry tomatoes, cook 2 min.","Add passata, season well. Simmer 8 min.","Drain pasta, reserve 1 cup pasta water. Toss pasta in sauce.","Fold in drained tuna gently. Add pasta water to loosen. Cook 1 min more.","Plate and finish with parsley and parmesan."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L2',
  'Salmon & Pea Rice Bowl',
  'lunch',
  1020, 58, 120, 26,
  '[{"name":"Basmati rice (dry)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salmon fillet","amount":"125g (1 fillet)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Frozen peas","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cucumber","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Spring onions","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Soy sauce (low sodium)","amount":"20ml","amount_value":20,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame oil","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic powder","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame seeds","amount":"5g","amount_value":5,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Cook rice. Add frozen peas to boiling water for last 3 min of rice cooking, or separately 3 min. Drain.","Season salmon with smoked paprika, garlic powder, salt. Pan-fry skin-side down 4 min, flip 2 min. Rest and flake.","Mix soy sauce and sesame oil as dressing.","Bowl: rice base, salmon, peas, sliced cucumber, spring onions.","Drizzle dressing, scatter sesame seeds."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L3',
  'Chicken & Chickpea Tomato Pasta',
  'lunch',
  1045, 67, 122, 21,
  '[{"name":"Fusilli (dry)","amount":"110g","amount_value":110,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Chicken breast","amount":"180g","amount_value":180,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned chickpeas (drained)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Canned chopped tomatoes","amount":"400g (1 tin)","amount_value":400,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red onion","amount":"½","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Dice chicken, season with paprika, salt, pepper. Cook in olive oil 6–7 min. Set aside.","Sauté diced onion and garlic 3 min. Add chickpeas and tomatoes, season with oregano. Simmer 8 min.","Cook pasta. Drain and add to sauce with chicken. Toss well.","Serve with parmesan."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L3b',
  'Chicken & Chickpea Tomato Pasta (extra chickpeas)',
  'lunch',
  980, 67, 105, 21,
  '[{"name":"Fusilli (dry)","amount":"75g","amount_value":75,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Chicken breast","amount":"180g","amount_value":180,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned chickpeas (drained)","amount":"120g (remainder from tin)","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Canned chopped tomatoes","amount":"400g (1 tin)","amount_value":400,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red onion","amount":"½","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Dice chicken, season with paprika, salt, pepper. Cook in olive oil 6–7 min. Set aside.","Sauté diced onion and garlic 3 min. Add chickpeas (remainder from earlier in week) and tomatoes, season with oregano. Simmer 8 min.","Cook pasta. Drain and add to sauce with chicken. Toss well.","Serve with parmesan."]'::jsonb,
  false,
  'Uses remainder of the chickpea tin opened earlier this week.'
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L4',
  'Tuna & Roasted Pepper Rice',
  'lunch',
  1030, 56, 130, 18,
  '[{"name":"Basmati rice (dry)","amount":"125g","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sweetcorn (tinned, drained)","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red pepper","amount":"1 large","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Yellow pepper","amount":"1 large","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cumin","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic powder","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Slice peppers, toss with half the oil and paprika. Roast 20 min.","Cook rice with cumin stirred into the water.","Mix tuna and sweetcorn with garlic powder, salt, pepper.","Bowl: rice, tuna-corn mix, roasted peppers. Drizzle remaining oil."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L5',
  'Tuna & Lentil Tomato Pasta',
  'lunch',
  1020, 60, 126, 16,
  '[{"name":"Spaghetti (dry)","amount":"110g","amount_value":110,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned green lentils (drained)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Passata","amount":"200ml","amount_value":200,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried thyme","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Cook spaghetti al dente. Reserve a cup of pasta water.","Sauté garlic in olive oil 1 min. Add passata, lentils, thyme. Simmer 8 min.","Drain pasta, add to sauce. Fold in drained tuna gently. Loosen with pasta water.","Finish with parmesan and black pepper."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L5b',
  'Tuna & Lentil Tomato Pasta (extra lentils)',
  'lunch',
  955, 60, 108, 16,
  '[{"name":"Spaghetti (dry)","amount":"75g","amount_value":75,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned green lentils (drained)","amount":"120g (remainder from tin)","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Passata","amount":"200ml","amount_value":200,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried thyme","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Cook spaghetti al dente. Reserve a cup of pasta water.","Sauté garlic in olive oil 1 min. Add passata, lentils (remainder from tin), thyme. Simmer 8 min.","Drain pasta, add to sauce. Fold in drained tuna gently. Loosen with pasta water.","Finish with parmesan and black pepper."]'::jsonb,
  false,
  'Uses remainder of the lentil tin opened earlier this week.'
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L6',
  'Chicken Fried Rice with Peas & Egg',
  'lunch',
  1055, 68, 116, 24,
  '[{"name":"Basmati rice (dry, cook day before ideally)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chicken breast","amount":"160g","amount_value":160,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Whole eggs","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Frozen peas","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Soy sauce (low sodium)","amount":"20ml","amount_value":20,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame oil","amount":"8ml","amount_value":8,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Spring onions","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Vegetable oil","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Cook and cool rice (day-old is best for texture).","Dice chicken, stir-fry in vegetable oil on high heat 5 min. Set aside.","Scramble eggs in same pan, barely set. Push to side.","Add garlic, peas, rice. Fry 3 min, stirring constantly.","Return chicken, add soy sauce and sesame oil. Toss. Top with spring onions."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L7',
  'Mackerel & Ricotta Pasta with Spinach',
  'lunch',
  1055, 54, 122, 34,
  '[{"name":"Rigatoni (dry)","amount":"115g","amount_value":115,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned mackerel in spring water/brine","amount":"125g (1 tin, drained)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Ricotta","amount":"125g","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried chilli flakes","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Nutmeg, grated","amount":"pinch","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Cook rigatoni al dente. Reserve a full cup of pasta water — the sauce needs it.","Sauté garlic and chilli in olive oil 1 min. Wilt spinach in same pan 2 min.","Reduce heat to low. Add ricotta and a ladleful of pasta water. Stir into a loose sauce.","Drain pasta, add to pan. Fold in flaked mackerel gently. Add more pasta water if needed.","Finish with parmesan, a grating of nutmeg, and black pepper."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L8',
  'Tofu & Vegetable Rice Stir-Fry',
  'lunch',
  970, 46, 120, 22,
  '[{"name":"Basmati rice (dry)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Firm tofu (extra firm)","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Frozen broccoli florets","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red pepper","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Soy sauce (low sodium)","amount":"25ml","amount_value":25,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame oil","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh ginger (grated)","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Vegetable oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame seeds","amount":"5g","amount_value":5,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Press tofu 15 min. Cube and fry in vegetable oil on high heat until golden, ~8 min. Set aside.","Cook rice.","Stir-fry garlic and ginger 30 sec. Add broccoli and pepper, fry 4 min on high.","Return tofu. Add soy sauce and sesame oil. Toss and serve over rice with sesame seeds."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L9',
  'Tuna Niçoise Rice Bowl',
  'lunch',
  1030, 58, 118, 24,
  '[{"name":"Basmati rice (dry)","amount":"110g","amount_value":110,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Green beans","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cherry tomatoes","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Whole eggs (hard-boiled)","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Black olives (pitted)","amount":"30g","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red wine vinegar","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dijon mustard","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Hard-boil eggs 9 min. Cool, peel, halve.","Cook rice. Blanch green beans 3 min in salted boiling water, drain.","Whisk olive oil, vinegar, mustard, salt, pepper as dressing.","Bowl: rice, tuna, green beans, halved tomatoes, eggs, olives. Drizzle dressing."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L10',
  'Salmon & Lentil Rice with Roasted Courgette',
  'lunch',
  1020, 58, 114, 24,
  '[{"name":"Basmati rice (dry)","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Salmon fillet","amount":"125g (1 fillet)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned green lentils (drained)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Courgette","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic powder","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried rosemary","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried dill","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Slice courgette, toss with half the oil, rosemary, salt. Roast 18 min.","Season salmon with paprika, salt. Pan-fry skin-side down 4 min, flip 2 min. Rest and flake.","Cook rice. Warm lentils with garlic powder and a splash of water.","Mix yogurt with dill, salt as a dressing.","Bowl: rice, lentils, salmon, roasted courgette. Drizzle yogurt dressing. Season well."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L10b',
  'Salmon & Lentil Rice with Roasted Courgette (extra lentils)',
  'lunch',
  958, 58, 97, 24,
  '[{"name":"Basmati rice (dry)","amount":"65g","amount_value":65,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Salmon fillet","amount":"125g (1 fillet)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned green lentils (drained)","amount":"120g (remainder from tin)","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Courgette","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic powder","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried rosemary","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried dill","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Slice courgette, toss with half the oil, rosemary, salt. Roast 18 min.","Season salmon with paprika, salt. Pan-fry skin-side down 4 min, flip 2 min. Rest and flake.","Cook rice. Warm lentils (remainder from tin) with garlic powder and a splash of water.","Mix yogurt with dill, salt as a dressing.","Bowl: rice, lentils, salmon, roasted courgette. Drizzle yogurt dressing. Season well."]'::jsonb,
  false,
  'Uses remainder of the lentil tin opened earlier this week.'
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L11',
  'Chicken & Roasted Vegetable Pasta with Ricotta',
  'lunch',
  1090, 70, 118, 30,
  '[{"name":"Penne (dry)","amount":"110g","amount_value":110,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chicken breast","amount":"180g","amount_value":180,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Ricotta","amount":"125g","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Courgette","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red pepper","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried basil","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Chop courgette and pepper, toss with half the oil and herbs. Roast 20 min.","Slice chicken, sauté in remaining oil with garlic 6–7 min until cooked through.","Cook pasta. Reserve a cup of pasta water before draining.","Reduce heat. Add ricotta to the chicken pan with a ladleful of pasta water. Stir into a loose sauce.","Add pasta and roasted veg. Toss well. Season generously, finish with parmesan."]'::jsonb,
  false,
  'Uses remainder of ricotta tub opened earlier this week.'
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L12',
  'Mackerel & Beetroot Rice Bowl',
  'lunch',
  1040, 48, 130, 26,
  '[{"name":"Basmati rice (dry)","amount":"115g","amount_value":115,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned mackerel in spring water/brine","amount":"125g (1 tin, drained)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Pre-cooked beetroot (plain)","amount":"250g","amount_value":250,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cucumber","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Rocket leaves","amount":"40g","amount_value":40,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red wine vinegar","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dijon mustard","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Cook rice, cool slightly.","Whisk olive oil, vinegar, mustard, salt as dressing.","Cube beetroot, slice cucumber.","Bowl: rice, rocket, beetroot, cucumber, flaked mackerel. Drizzle dressing."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L13',
  'Tuna & White Bean Stew with Rice',
  'lunch',
  1000, 62, 118, 12,
  '[{"name":"Basmati rice (dry)","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned cannellini beans (drained)","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Canned chopped tomatoes","amount":"400g (1 tin)","amount_value":400,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red onion","amount":"½","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried thyme","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Bay leaf","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Sauté diced onion and garlic in olive oil 3 min.","Add tomatoes, beans, thyme, bay leaf. Simmer 10 min.","Fold in drained tuna. Simmer 2 min more.","Cook rice separately. Serve stew over rice."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L13b',
  'Tuna & White Bean Stew with Rice (extra beans)',
  'lunch',
  968, 65, 100, 18,
  '[{"name":"Basmati rice (dry)","amount":"65g","amount_value":65,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":true},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned cannellini beans (drained)","amount":"120g (remainder from tin)","amount_value":120,"amount_unit":"g","is_tin_ingredient":true,"is_carb_adjust":false},{"name":"Canned chopped tomatoes","amount":"400g (1 tin)","amount_value":400,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red onion","amount":"½","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried thyme","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Bay leaf","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Sauté diced onion and garlic in olive oil 3 min.","Add tomatoes, beans (remainder from tin), thyme, bay leaf. Simmer 10 min.","Fold in drained tuna. Simmer 2 min more.","Cook rice separately. Serve stew over rice."]'::jsonb,
  false,
  'Uses remainder of the cannellini bean tin opened earlier this week.'
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L14',
  'Egg Fried Noodles with Peas & Tofu',
  'lunch',
  1040, 58, 118, 28,
  '[{"name":"Rice noodles (dry)","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Firm tofu","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Whole eggs","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Frozen peas","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Spring onions","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Soy sauce (low sodium)","amount":"25ml","amount_value":25,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame oil","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Vegetable oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame seeds","amount":"5g","amount_value":5,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Soak noodles per packet. Press and cube tofu, fry in vegetable oil until golden. Set aside.","Cook frozen peas in boiling water 3 min. Drain.","Scramble eggs in wok, barely set. Add garlic 30 sec.","Add noodles, peas, tofu. Toss on high heat. Add soy sauce and sesame oil.","Top with spring onions and sesame seeds."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L15',
  'Tuna, Ricotta & Spinach Wraps',
  'lunch',
  830, 53, 77, 30,
  '[{"name":"Plain tortilla wraps","amount":"2 wraps","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Ricotta","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"40g","amount_value":40,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"15g","amount_value":15,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"8ml","amount_value":8,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Rocket leaves","amount":"30g","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cucumber","amount":"60g","amount_value":60,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & black pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Mix ricotta with a pinch of salt and pepper. Spread evenly over both wraps.","Top each with spinach leaves, drained tuna, and grated parmesan.","Fold wraps and toast in a dry pan on medium heat 2–3 min per side until golden and slightly crisp.","Serve alongside a simple rocket and cucumber salad dressed with olive oil and salt."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L16',
  'Chicken, Roasted Pepper & Parmesan Wraps',
  'lunch',
  820, 50, 82, 26,
  '[{"name":"Plain tortilla wraps","amount":"2 wraps","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chicken breast","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red pepper","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Parmesan, finely grated","amount":"20g","amount_value":20,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Rocket leaves","amount":"30g","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Slice chicken thinly. Season with paprika, oregano, salt. Pan-fry in half the oil 5–6 min until cooked through. Rest and slice.","Slice pepper into strips, char in same pan 3–4 min. Remove.","Lay chicken, roasted pepper, and parmesan onto wraps. Season.","Fold and toast in a dry pan 2–3 min per side until golden.","Serve with rocket dressed with remaining olive oil."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L17',
  'Salmon, Cottage Cheese & Cucumber Wraps',
  'lunch',
  790, 48, 77, 24,
  '[{"name":"Plain tortilla wraps","amount":"2 wraps","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salmon fillet","amount":"125g (1 fillet)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cottage cheese","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cucumber","amount":"80g","amount_value":80,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"40g","amount_value":40,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried dill","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"8ml","amount_value":8,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Rocket leaves","amount":"30g","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & black pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Season salmon with salt and pepper. Pan-fry skin-side down 4 min, flip 2 min. Rest, then flake.","Mix cottage cheese with dill and a pinch of pepper. Spread over both wraps.","Top with spinach, flaked salmon, and sliced cucumber.","Fold and toast in a dry pan 2 min per side — gentle heat so the cottage cheese doesn''t leak.","Serve with rocket dressed with olive oil."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'L18',
  'Mackerel, Mozzarella & Courgette Wraps',
  'lunch',
  860, 43, 77, 36,
  '[{"name":"Plain tortilla wraps","amount":"2 wraps","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned mackerel in spring water/brine","amount":"125g (1 tin, drained)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Mozzarella (block or slices)","amount":"50g","amount_value":50,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Courgette","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried chilli flakes","amount":"¼ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Rocket leaves","amount":"30g","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Slice courgette into thin rounds. Pan-fry in oil with oregano and chilli 4 min until golden. Season.","Lay flaked mackerel, courgette slices, and torn mozzarella onto wraps.","Fold and toast in a dry pan on medium heat 2–3 min per side until mozzarella melts and wrap is crisp.","Serve with dressed rocket alongside."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D1',
  'Greek Yogurt Bowl with Roasted Veg',
  'dinner',
  800, 52, 60, 30,
  '[{"name":"Full-fat Greek yogurt","amount":"300g","amount_value":300,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Courgette","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red pepper","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cherry tomatoes","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Black olives (pitted)","amount":"30g","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Chop courgette and pepper, toss with oil, oregano, paprika, salt. Roast 20 min.","Spread Greek yogurt in a wide bowl as base.","Top with roasted veg, halved cherry tomatoes, olives. Season with black pepper."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D2',
  'Pan-Fried Salmon with Broccoli & Mustard Yogurt',
  'dinner',
  760, 52, 18, 34,
  '[{"name":"Salmon fillet","amount":"125g (1 fillet)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Frozen broccoli","amount":"300g","amount_value":300,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic powder","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dijon mustard","amount":"2 tsp","amount_value":2,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Season salmon with garlic powder, smoked paprika, salt. Pan-fry skin-side down 4 min, flip 2 min.","Steam broccoli 5 min. Drain well.","Mix yogurt with mustard, garlic powder, salt into a thick sauce.","Plate: broccoli alongside salmon, yogurt sauce spooned over generously."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D3',
  'Tofu & Spinach Scramble with Eggs',
  'dinner',
  730, 44, 18, 36,
  '[{"name":"Firm tofu","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chestnut mushrooms","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Whole eggs","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Turmeric","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cumin","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Soy sauce (low sodium)","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Crumble tofu. Slice mushrooms.","Heat oil on high. Fry mushrooms 4 min until browned. Add garlic 1 min.","Add crumbled tofu, turmeric, cumin, soy sauce. Fry 3 min.","Crack in eggs, scramble through. Wilt spinach. Season well."]'::jsonb,
  true,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D4',
  'Baked Chicken with Green Beans & Tzatziki',
  'dinner',
  810, 70, 20, 26,
  '[{"name":"Chicken breast","amount":"220g","amount_value":220,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Green beans","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cucumber","amount":"60g","amount_value":60,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried dill","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red wine vinegar","amount":"5ml","amount_value":5,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Rub chicken with oil, paprika, salt, pepper. Bake 22–25 min.","Blanch green beans in salted boiling water 4 min. Drain, toss with a little oil.","Tzatziki: grate cucumber, squeeze out water. Mix with yogurt, 2 grated garlic cloves, dill, salt.","Slice chicken. Serve with green beans and tzatziki."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D5',
  'Frittata with Cottage Cheese & Roasted Tomatoes',
  'dinner',
  790, 56, 16, 40,
  '[{"name":"Whole eggs","amount":"4","amount_value":4,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cottage cheese","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cherry tomatoes","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chestnut mushrooms","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried thyme","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 180°C. Roast halved cherry tomatoes with a little oil and thyme 15 min.","Sauté mushrooms and garlic in oven-proof pan 4 min. Wilt spinach.","Whisk eggs with cottage cheese, salt, pepper. Pour over mushrooms.","Hob 2 min until edges set. Transfer to oven 10–12 min until set through.","Slide out, top with roasted tomatoes."]'::jsonb,
  true,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D6',
  'Tuna with Cauliflower Mash & Green Beans',
  'dinner',
  800, 62, 30, 26,
  '[{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cauliflower","amount":"300g","amount_value":300,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Green beans","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dijon mustard","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Steam cauliflower 10 min until very soft. Blend with yogurt, garlic, mustard, salt until smooth.","Blanch green beans 4 min in salted water. Drain.","Plate: cauliflower mash, green beans alongside, drained tuna on top."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D7',
  'Chicken Stir-Fry with Pak Choi & Mushrooms',
  'dinner',
  800, 68, 22, 28,
  '[{"name":"Chicken breast","amount":"220g","amount_value":220,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Pak choi","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chestnut mushrooms","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh ginger","amount":"1 tsp grated","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Soy sauce (low sodium)","amount":"20ml","amount_value":20,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame oil","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Vegetable oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Spring onions","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame seeds","amount":"5g","amount_value":5,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Slice chicken into strips. Marinate in half the soy sauce 10 min.","High-heat wok. Fry chicken 5 min. Set aside.","Fry garlic and ginger 30 sec. Add mushrooms 3 min. Add pak choi, remaining soy, sesame oil. Toss 2 min.","Return chicken. Top with spring onions and sesame seeds."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D8',
  'Salmon with Wilted Spinach & Cottage Cheese Sauce',
  'dinner',
  720, 54, 12, 36,
  '[{"name":"Salmon fillet","amount":"125g (1 fillet)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cottage cheese","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried dill","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & black pepper","amount":"generous","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Pan-fry salmon in olive oil, 4 min skin side, 2 min flip. Rest.","Sauté garlic 30 sec in same pan. Wilt spinach 2 min. Season.","Blend cottage cheese with dill, salt, pepper until smooth. Warm gently.","Plate: spinach base, salmon on top, cottage cheese sauce spooned over."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D9',
  'Egg & Vegetable Shakshuka',
  'dinner',
  780, 46, 36, 32,
  '[{"name":"Whole eggs","amount":"4","amount_value":4,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Canned chopped tomatoes","amount":"400g (1 tin)","amount_value":400,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red pepper","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Courgette","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cumin","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Chilli flakes","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Sauté diced pepper, courgette, garlic in olive oil 5 min.","Add spices, cook 1 min. Add tomatoes, season. Simmer 10 min.","Make 4 wells in sauce. Crack in eggs. Cover, cook 6–8 min until whites set, yolks still soft.","Serve straight from pan."]'::jsonb,
  true,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D10',
  'Tofu & Broccoli with Miso-Sesame Dressing',
  'dinner',
  700, 40, 24, 30,
  '[{"name":"Firm tofu","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Frozen broccoli","amount":"250g","amount_value":250,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"White miso paste","amount":"20g","amount_value":20,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Soy sauce","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Rice vinegar","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic clove","amount":"1","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Vegetable oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sesame seeds","amount":"8g","amount_value":8,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Press and cube tofu. Fry in vegetable oil until golden all sides, ~8 min.","Steam broccoli 5 min. Drain.","Whisk miso, sesame oil, soy, rice vinegar, grated garlic. Add hot water to thin.","Arrange tofu and broccoli. Drizzle dressing. Top with sesame seeds."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D11',
  'Chicken with Roasted Courgette & Soft-Boiled Eggs',
  'dinner',
  800, 70, 14, 32,
  '[{"name":"Chicken breast","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Courgette","amount":"250g","amount_value":250,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Whole eggs (soft-boiled)","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dijon mustard","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red wine vinegar","amount":"5ml","amount_value":5,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Slice courgette, toss with half the oil, oregano, salt. Roast 20 min.","Soft-boil eggs 6 min. Ice water, peel.","Season chicken with paprika, salt. Pan-fry 6 min each side. Rest 2 min, slice.","Whisk remaining oil, mustard, vinegar, garlic as dressing.","Plate: courgette, chicken, halved eggs. Drizzle dressing."]'::jsonb,
  true,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D12',
  'Mackerel with Beetroot & Greek Yogurt',
  'dinner',
  820, 48, 36, 38,
  '[{"name":"Canned mackerel in spring water/brine","amount":"125g (1 tin, drained)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Pre-cooked beetroot (plain)","amount":"250g","amount_value":250,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Rocket leaves","amount":"60g","amount_value":60,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red wine vinegar","amount":"10ml","amount_value":10,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried dill","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Slice beetroot, drizzle with a little oil and vinegar.","Season yogurt with dill, salt, pepper. Spread on plate.","Top with rocket, beetroot, flaked mackerel. Drizzle remaining oil."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D13',
  'Cottage Cheese & Egg Stuffed Peppers',
  'dinner',
  770, 52, 28, 34,
  '[{"name":"Large red peppers","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Whole eggs","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cottage cheese","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 190°C. Halve peppers, remove seeds. Place cut-side up in baking dish.","Sauté garlic in olive oil 1 min. Wilt spinach. Season.","Whisk eggs with cottage cheese, oregano, salt, pepper. Stir in spinach.","Divide into pepper halves. Bake 25–28 min until filling set and peppers soft."]'::jsonb,
  true,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D14',
  'Tuna with Courgette & Feta Yogurt',
  'dinner',
  800, 64, 20, 30,
  '[{"name":"Canned tuna in spring water","amount":"145g (1 tin, drained)","amount_value":145,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Courgette","amount":"200g","amount_value":200,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Feta cheese (crumbled)","amount":"30g","amount_value":30,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried mint","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cherry tomatoes","amount":"100g","amount_value":100,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Slice courgette, fry in same pan with garlic until golden, 5 min. Add halved cherry tomatoes, cook 2 min.","Mix yogurt with crumbled feta, mint, pinch of salt.","Plate: courgette and tomatoes, drained tuna on top, feta yogurt alongside."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D8b',
  'Salmon with Spinach & Cottage Cheese Sauce',
  'dinner',
  720, 54, 12, 36,
  '[{"name":"Salmon fillet","amount":"125g (1 fillet)","amount_value":125,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Fresh spinach","amount":"120g","amount_value":120,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cottage cheese","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried dill","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & black pepper","amount":"generous","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Pan-fry salmon in olive oil, 4 min skin side, 2 min flip. Rest.","Sauté garlic 30 sec. Wilt spinach 2 min. Season.","Blend cottage cheese with paprika, dill, salt, pepper. Warm gently.","Plate: spinach base, salmon on top, cottage cheese sauce spooned over."]'::jsonb,
  false,
  'Uses remainder of cottage cheese tub opened with D13 earlier this week.'
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D15',
  'Chicken with Roasted Red Peppers & Yogurt',
  'dinner',
  790, 68, 22, 28,
  '[{"name":"Chicken breast","amount":"220g","amount_value":220,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Red pepper","amount":"2","amount_value":2,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cherry tomatoes","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"15ml","amount_value":15,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Garlic cloves","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Smoked paprika","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cumin","amount":"½ tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Dried oregano","amount":"1 tsp","amount_value":1,"amount_unit":"tsp","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Preheat oven 200°C. Slice peppers, toss with half the oil, paprika, salt. Roast 20 min.","Season chicken with cumin, oregano, salt. Pan-fry 6 min each side. Rest 2 min.","Halve cherry tomatoes, toss in remaining oil with garlic. Add to oven last 10 min.","Slice chicken. Serve with roasted peppers and tomatoes, yogurt alongside."]'::jsonb,
  false,
  null
);

insert into public.recipes (slug, name, type, kcal, protein_g, carbs_g, fat_g, ingredients, steps, is_egg_dinner, tin_note) values (
  'D16',
  'Egg & Sweetcorn Scramble with Sriracha',
  'dinner',
  738, 48, 53, 38,
  '[{"name":"Whole eggs","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Egg whites","amount":"3 whites (from ~3 eggs)","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sweetcorn (tinned, drained)","amount":"198g (1 tin)","amount_value":198,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Cherry tomatoes","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Spring onions","amount":"3","amount_value":3,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Full-fat Greek yogurt","amount":"150g","amount_value":150,"amount_unit":"g","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Olive oil","amount":"12ml","amount_value":12,"amount_unit":"ml","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Sriracha","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false},{"name":"Salt & black pepper","amount":"to taste","amount_value":1,"amount_unit":"units","is_tin_ingredient":false,"is_carb_adjust":false}]'::jsonb,
  '["Separate 3 eggs — keep the yolks with the whole eggs. Whisk all 6 eggs (3 whole + 3 whites) together with salt and pepper.","Heat olive oil in a wide pan over medium-high. Add sweetcorn and halved cherry tomatoes. Cook 3–4 min until tomatoes soften and sweetcorn gets a little colour.","Pour in egg mixture. Let it set slightly at the edges, then fold gently with a spatula — you want soft, large curds, not a dry scramble. Pull off heat while still slightly glossy.","Slice spring onions. Scatter over the top along with a generous drizzle of sriracha.","Serve with Greek yogurt on the side to temper the heat."]'::jsonb,
  true,
  null
);

insert into public.recipe_pairs (shared_resource, primary_recipe_id, secondary_recipe_id, carb_ingredient_name, primary_carb_amount, secondary_carb_amount) values (
  'chickpeas-A',
  (select id from public.recipes where slug = 'L3'),
  (select id from public.recipes where slug = 'L3b'),
  'Fusilli (dry)',
  '110g',
  '75g'
);

insert into public.recipe_pairs (shared_resource, primary_recipe_id, secondary_recipe_id, carb_ingredient_name, primary_carb_amount, secondary_carb_amount) values (
  'lentils-A',
  (select id from public.recipes where slug = 'L5'),
  (select id from public.recipes where slug = 'L5b'),
  'Spaghetti (dry)',
  '110g',
  '75g'
);

insert into public.recipe_pairs (shared_resource, primary_recipe_id, secondary_recipe_id, carb_ingredient_name, primary_carb_amount, secondary_carb_amount) values (
  'lentils-B',
  (select id from public.recipes where slug = 'L10'),
  (select id from public.recipes where slug = 'L10b'),
  'Basmati rice (dry)',
  '100g',
  '65g'
);

insert into public.recipe_pairs (shared_resource, primary_recipe_id, secondary_recipe_id, carb_ingredient_name, primary_carb_amount, secondary_carb_amount) values (
  'whitebeans-A',
  (select id from public.recipes where slug = 'L13'),
  (select id from public.recipes where slug = 'L13b'),
  'Basmati rice (dry)',
  '100g',
  '65g'
);

insert into public.recipe_pairs (shared_resource, primary_recipe_id, secondary_recipe_id, carb_ingredient_name, primary_carb_amount, secondary_carb_amount) values (
  'ricotta-A',
  (select id from public.recipes where slug = 'L7'),
  (select id from public.recipes where slug = 'L11'),
  null,
  null,
  null
);

insert into public.recipe_pairs (shared_resource, primary_recipe_id, secondary_recipe_id, carb_ingredient_name, primary_carb_amount, secondary_carb_amount) values (
  'cc-A',
  (select id from public.recipes where slug = 'D5'),
  (select id from public.recipes where slug = 'D8'),
  null,
  null,
  null
);

insert into public.recipe_pairs (shared_resource, primary_recipe_id, secondary_recipe_id, carb_ingredient_name, primary_carb_amount, secondary_carb_amount) values (
  'cc-B',
  (select id from public.recipes where slug = 'D13'),
  (select id from public.recipes where slug = 'D8b'),
  null,
  null,
  null
);

commit;
